version: "3.9"

services:
  database: #ESSE É O NOME DO SERVICE QUE DEVE ESTAR NO ARQUIVO DE CRIAÇÃO DE CONEXÃO
    image: postgres
    container_name: ignite-challenge-database-queries
    restart: always
    ports: 
      - 5433:5433
    expose: 
      - 5433
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=queries_challenge
    volumes:
      - pgdata:/data/postgres
    command: -p 5433

volumes:
  pgdata:
    driver: local
